// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	cline "github.com/cline/cli/pkg/generated/cline"
	proto "github.com/cline/cli/pkg/generated/cline"
	"google.golang.org/grpc"
)

// AccountClient wraps the generated AccountService gRPC client
type AccountClient struct {
	client proto.AccountServiceClient
}

// NewAccountClient creates a new AccountClient
func NewAccountClient(conn *grpc.ClientConn) *AccountClient {
	return &AccountClient{
		client: proto.NewAccountServiceClient(conn),
	}
}

// AccountLoginClicked retrieves the current application accountLoginClicked
func (sc *AccountClient) AccountLoginClicked(ctx context.Context, req *cline.EmptyRequest) (*cline.String, error) {
	resp, err := sc.client.AccountLoginClicked(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest accountLoginClicked: %w", err)
	}

	return resp, nil
}

// AccountLogoutClicked retrieves the current application accountLogoutClicked
func (sc *AccountClient) AccountLogoutClicked(ctx context.Context, req *cline.EmptyRequest) (*cline.Empty, error) {
	resp, err := sc.client.AccountLogoutClicked(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest accountLogoutClicked: %w", err)
	}

	return resp, nil
}

// SubscribeToAuthStatusUpdate subscribes to subscribeToAuthStatusUpdate updates and returns a stream
func (sc *AccountClient) SubscribeToAuthStatusUpdate(ctx context.Context, req *cline.EmptyRequest) (proto.AccountService_SubscribeToAuthStatusUpdateClient, error) {
	stream, err := sc.client.SubscribeToAuthStatusUpdate(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to subscribeToAuthStatusUpdate: %w", err)
	}

	return stream, nil
}

// AuthStateChanged retrieves the current application authStateChanged
func (sc *AccountClient) AuthStateChanged(ctx context.Context, req *proto.AuthStateChangedRequest) (*proto.AuthState, error) {
	resp, err := sc.client.AuthStateChanged(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest authStateChanged: %w", err)
	}

	return resp, nil
}

// GetUserCredits retrieves the current application getUserCredits
func (sc *AccountClient) GetUserCredits(ctx context.Context, req *cline.EmptyRequest) (*proto.UserCreditsData, error) {
	resp, err := sc.client.GetUserCredits(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getUserCredits: %w", err)
	}

	return resp, nil
}

// GetOrganizationCredits retrieves the current application getOrganizationCredits
func (sc *AccountClient) GetOrganizationCredits(ctx context.Context, req *proto.GetOrganizationCreditsRequest) (*proto.OrganizationCreditsData, error) {
	resp, err := sc.client.GetOrganizationCredits(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getOrganizationCredits: %w", err)
	}

	return resp, nil
}

// GetUserOrganizations retrieves the current application getUserOrganizations
func (sc *AccountClient) GetUserOrganizations(ctx context.Context, req *cline.EmptyRequest) (*proto.UserOrganizationsResponse, error) {
	resp, err := sc.client.GetUserOrganizations(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getUserOrganizations: %w", err)
	}

	return resp, nil
}

// SetUserOrganization retrieves the current application setUserOrganization
func (sc *AccountClient) SetUserOrganization(ctx context.Context, req *proto.UserOrganizationUpdateRequest) (*cline.Empty, error) {
	resp, err := sc.client.SetUserOrganization(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest setUserOrganization: %w", err)
	}

	return resp, nil
}

// OpenrouterAuthClicked retrieves the current application openrouterAuthClicked
func (sc *AccountClient) OpenrouterAuthClicked(ctx context.Context, req *cline.EmptyRequest) (*cline.Empty, error) {
	resp, err := sc.client.OpenrouterAuthClicked(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest openrouterAuthClicked: %w", err)
	}

	return resp, nil
}

// GetRedirectUrl retrieves the current application getRedirectUrl
func (sc *AccountClient) GetRedirectUrl(ctx context.Context, req *cline.EmptyRequest) (*cline.String, error) {
	resp, err := sc.client.GetRedirectUrl(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getRedirectUrl: %w", err)
	}

	return resp, nil
}
