// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	cline "github.com/cline/cli/pkg/generated/cline"
	proto "github.com/cline/cli/pkg/generated/cline"
	"google.golang.org/grpc"
)

// BrowserClient wraps the generated BrowserService gRPC client
type BrowserClient struct {
	client proto.BrowserServiceClient
}

// NewBrowserClient creates a new BrowserClient
func NewBrowserClient(conn *grpc.ClientConn) *BrowserClient {
	return &BrowserClient{
		client: proto.NewBrowserServiceClient(conn),
	}
}

// GetBrowserConnectionInfo retrieves the current application getBrowserConnectionInfo
func (sc *BrowserClient) GetBrowserConnectionInfo(ctx context.Context, req *cline.EmptyRequest) (*proto.BrowserConnectionInfo, error) {
	resp, err := sc.client.GetBrowserConnectionInfo(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getBrowserConnectionInfo: %w", err)
	}

	return resp, nil
}

// TestBrowserConnection retrieves the current application testBrowserConnection
func (sc *BrowserClient) TestBrowserConnection(ctx context.Context, req *cline.StringRequest) (*proto.BrowserConnection, error) {
	resp, err := sc.client.TestBrowserConnection(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest testBrowserConnection: %w", err)
	}

	return resp, nil
}

// DiscoverBrowser retrieves the current application discoverBrowser
func (sc *BrowserClient) DiscoverBrowser(ctx context.Context, req *cline.EmptyRequest) (*proto.BrowserConnection, error) {
	resp, err := sc.client.DiscoverBrowser(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest discoverBrowser: %w", err)
	}

	return resp, nil
}

// GetDetectedChromePath retrieves the current application getDetectedChromePath
func (sc *BrowserClient) GetDetectedChromePath(ctx context.Context, req *cline.EmptyRequest) (*proto.ChromePath, error) {
	resp, err := sc.client.GetDetectedChromePath(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getDetectedChromePath: %w", err)
	}

	return resp, nil
}

// RelaunchChromeDebugMode retrieves the current application relaunchChromeDebugMode
func (sc *BrowserClient) RelaunchChromeDebugMode(ctx context.Context, req *cline.EmptyRequest) (*cline.String, error) {
	resp, err := sc.client.RelaunchChromeDebugMode(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest relaunchChromeDebugMode: %w", err)
	}

	return resp, nil
}
