// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	cline "github.com/cline/cli/pkg/generated/cline"
	proto "github.com/cline/cli/pkg/generated/cline"
	"google.golang.org/grpc"
)

// CheckpointsClient wraps the generated CheckpointsService gRPC client
type CheckpointsClient struct {
	client proto.CheckpointsServiceClient
}

// NewCheckpointsClient creates a new CheckpointsClient
func NewCheckpointsClient(conn *grpc.ClientConn) *CheckpointsClient {
	return &CheckpointsClient{
		client: proto.NewCheckpointsServiceClient(conn),
	}
}

// CheckpointDiff retrieves the current application checkpointDiff
func (sc *CheckpointsClient) CheckpointDiff(ctx context.Context, req *cline.Int64Request) (*cline.Empty, error) {
	resp, err := sc.client.CheckpointDiff(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest checkpointDiff: %w", err)
	}

	return resp, nil
}

// CheckpointRestore retrieves the current application checkpointRestore
func (sc *CheckpointsClient) CheckpointRestore(ctx context.Context, req *proto.CheckpointRestoreRequest) (*cline.Empty, error) {
	resp, err := sc.client.CheckpointRestore(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest checkpointRestore: %w", err)
	}

	return resp, nil
}

// SubscribeToCheckpoints subscribes to subscribeToCheckpoints updates and returns a stream
func (sc *CheckpointsClient) SubscribeToCheckpoints(ctx context.Context, req *proto.CheckpointSubscriptionRequest) (proto.CheckpointsService_SubscribeToCheckpointsClient, error) {
	stream, err := sc.client.SubscribeToCheckpoints(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to subscribeToCheckpoints: %w", err)
	}

	return stream, nil
}

// GetCwdHash retrieves the current application getCwdHash
func (sc *CheckpointsClient) GetCwdHash(ctx context.Context, req *proto.StringArrayRequest) (*proto.PathHashMap, error) {
	resp, err := sc.client.GetCwdHash(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getCwdHash: %w", err)
	}

	return resp, nil
}
