// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	cline "github.com/cline/cli/pkg/generated/cline"
	proto "github.com/cline/cli/pkg/generated/cline"
	"google.golang.org/grpc"
)

// CommandsClient wraps the generated CommandsService gRPC client
type CommandsClient struct {
	client proto.CommandsServiceClient
}

// NewCommandsClient creates a new CommandsClient
func NewCommandsClient(conn *grpc.ClientConn) *CommandsClient {
	return &CommandsClient{
		client: proto.NewCommandsServiceClient(conn),
	}
}

// AddToCline retrieves the current application addToCline
func (sc *CommandsClient) AddToCline(ctx context.Context, req *proto.CommandContext) (*cline.Empty, error) {
	resp, err := sc.client.AddToCline(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest addToCline: %w", err)
	}

	return resp, nil
}

// FixWithCline retrieves the current application fixWithCline
func (sc *CommandsClient) FixWithCline(ctx context.Context, req *proto.CommandContext) (*cline.Empty, error) {
	resp, err := sc.client.FixWithCline(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest fixWithCline: %w", err)
	}

	return resp, nil
}

// ExplainWithCline retrieves the current application explainWithCline
func (sc *CommandsClient) ExplainWithCline(ctx context.Context, req *proto.CommandContext) (*cline.Empty, error) {
	resp, err := sc.client.ExplainWithCline(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest explainWithCline: %w", err)
	}

	return resp, nil
}

// ImproveWithCline retrieves the current application improveWithCline
func (sc *CommandsClient) ImproveWithCline(ctx context.Context, req *proto.CommandContext) (*cline.Empty, error) {
	resp, err := sc.client.ImproveWithCline(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest improveWithCline: %w", err)
	}

	return resp, nil
}
