// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	cline "github.com/cline/cli/pkg/generated/cline"
	proto "github.com/cline/cli/pkg/generated/cline"
	"google.golang.org/grpc"
)

// DictationClient wraps the generated DictationService gRPC client
type DictationClient struct {
	client proto.DictationServiceClient
}

// NewDictationClient creates a new DictationClient
func NewDictationClient(conn *grpc.ClientConn) *DictationClient {
	return &DictationClient{
		client: proto.NewDictationServiceClient(conn),
	}
}

// StartRecording retrieves the current application startRecording
func (sc *DictationClient) StartRecording(ctx context.Context, req *cline.EmptyRequest) (*proto.RecordingResult, error) {
	resp, err := sc.client.StartRecording(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest startRecording: %w", err)
	}

	return resp, nil
}

// StopRecording retrieves the current application stopRecording
func (sc *DictationClient) StopRecording(ctx context.Context, req *cline.EmptyRequest) (*proto.RecordedAudio, error) {
	resp, err := sc.client.StopRecording(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest stopRecording: %w", err)
	}

	return resp, nil
}

// CancelRecording retrieves the current application cancelRecording
func (sc *DictationClient) CancelRecording(ctx context.Context, req *cline.EmptyRequest) (*proto.RecordingResult, error) {
	resp, err := sc.client.CancelRecording(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest cancelRecording: %w", err)
	}

	return resp, nil
}

// GetRecordingStatus retrieves the current application getRecordingStatus
func (sc *DictationClient) GetRecordingStatus(ctx context.Context, req *cline.EmptyRequest) (*proto.RecordingStatus, error) {
	resp, err := sc.client.GetRecordingStatus(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getRecordingStatus: %w", err)
	}

	return resp, nil
}

// TranscribeAudio retrieves the current application transcribeAudio
func (sc *DictationClient) TranscribeAudio(ctx context.Context, req *proto.TranscribeAudioRequest) (*proto.Transcription, error) {
	resp, err := sc.client.TranscribeAudio(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest transcribeAudio: %w", err)
	}

	return resp, nil
}
