// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	proto "github.com/cline/cli/pkg/generated/host"
	"google.golang.org/grpc"
)

// DiffClient wraps the generated DiffService gRPC client
type DiffClient struct {
	client proto.DiffServiceClient
}

// NewDiffClient creates a new DiffClient
func NewDiffClient(conn *grpc.ClientConn) *DiffClient {
	return &DiffClient{
		client: proto.NewDiffServiceClient(conn),
	}
}

// OpenDiff retrieves the current application openDiff
func (sc *DiffClient) OpenDiff(ctx context.Context, req *proto.OpenDiffRequest) (*proto.OpenDiffResponse, error) {
	resp, err := sc.client.OpenDiff(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest openDiff: %w", err)
	}

	return resp, nil
}

// GetDocumentText retrieves the current application getDocumentText
func (sc *DiffClient) GetDocumentText(ctx context.Context, req *proto.GetDocumentTextRequest) (*proto.GetDocumentTextResponse, error) {
	resp, err := sc.client.GetDocumentText(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getDocumentText: %w", err)
	}

	return resp, nil
}

// ReplaceText retrieves the current application replaceText
func (sc *DiffClient) ReplaceText(ctx context.Context, req *proto.ReplaceTextRequest) (*proto.ReplaceTextResponse, error) {
	resp, err := sc.client.ReplaceText(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest replaceText: %w", err)
	}

	return resp, nil
}

// ScrollDiff retrieves the current application scrollDiff
func (sc *DiffClient) ScrollDiff(ctx context.Context, req *proto.ScrollDiffRequest) (*proto.ScrollDiffResponse, error) {
	resp, err := sc.client.ScrollDiff(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest scrollDiff: %w", err)
	}

	return resp, nil
}

// TruncateDocument retrieves the current application truncateDocument
func (sc *DiffClient) TruncateDocument(ctx context.Context, req *proto.TruncateDocumentRequest) (*proto.TruncateDocumentResponse, error) {
	resp, err := sc.client.TruncateDocument(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest truncateDocument: %w", err)
	}

	return resp, nil
}

// SaveDocument retrieves the current application saveDocument
func (sc *DiffClient) SaveDocument(ctx context.Context, req *proto.SaveDocumentRequest) (*proto.SaveDocumentResponse, error) {
	resp, err := sc.client.SaveDocument(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest saveDocument: %w", err)
	}

	return resp, nil
}

// CloseAllDiffs retrieves the current application closeAllDiffs
func (sc *DiffClient) CloseAllDiffs(ctx context.Context, req *proto.CloseAllDiffsRequest) (*proto.CloseAllDiffsResponse, error) {
	resp, err := sc.client.CloseAllDiffs(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest closeAllDiffs: %w", err)
	}

	return resp, nil
}

// OpenMultiFileDiff retrieves the current application openMultiFileDiff
func (sc *DiffClient) OpenMultiFileDiff(ctx context.Context, req *proto.OpenMultiFileDiffRequest) (*proto.OpenMultiFileDiffResponse, error) {
	resp, err := sc.client.OpenMultiFileDiff(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest openMultiFileDiff: %w", err)
	}

	return resp, nil
}
