// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	cline "github.com/cline/cli/pkg/generated/cline"
	proto "github.com/cline/cli/pkg/generated/host"
	"google.golang.org/grpc"
)

// EnvClient wraps the generated EnvService gRPC client
type EnvClient struct {
	client proto.EnvServiceClient
}

// NewEnvClient creates a new EnvClient
func NewEnvClient(conn *grpc.ClientConn) *EnvClient {
	return &EnvClient{
		client: proto.NewEnvServiceClient(conn),
	}
}

// ClipboardWriteText retrieves the current application clipboardWriteText
func (sc *EnvClient) ClipboardWriteText(ctx context.Context, req *cline.StringRequest) (*cline.Empty, error) {
	resp, err := sc.client.ClipboardWriteText(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest clipboardWriteText: %w", err)
	}

	return resp, nil
}

// ClipboardReadText retrieves the current application clipboardReadText
func (sc *EnvClient) ClipboardReadText(ctx context.Context, req *cline.EmptyRequest) (*cline.String, error) {
	resp, err := sc.client.ClipboardReadText(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest clipboardReadText: %w", err)
	}

	return resp, nil
}

// GetHostVersion retrieves the current application getHostVersion
func (sc *EnvClient) GetHostVersion(ctx context.Context, req *cline.EmptyRequest) (*proto.GetHostVersionResponse, error) {
	resp, err := sc.client.GetHostVersion(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getHostVersion: %w", err)
	}

	return resp, nil
}

// GetIdeRedirectUri retrieves the current application getIdeRedirectUri
func (sc *EnvClient) GetIdeRedirectUri(ctx context.Context, req *cline.EmptyRequest) (*cline.String, error) {
	resp, err := sc.client.GetIdeRedirectUri(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getIdeRedirectUri: %w", err)
	}

	return resp, nil
}

// GetTelemetrySettings retrieves the current application getTelemetrySettings
func (sc *EnvClient) GetTelemetrySettings(ctx context.Context, req *cline.EmptyRequest) (*proto.GetTelemetrySettingsResponse, error) {
	resp, err := sc.client.GetTelemetrySettings(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getTelemetrySettings: %w", err)
	}

	return resp, nil
}

// SubscribeToTelemetrySettings subscribes to subscribeToTelemetrySettings updates and returns a stream
func (sc *EnvClient) SubscribeToTelemetrySettings(ctx context.Context, req *cline.EmptyRequest) (proto.EnvService_SubscribeToTelemetrySettingsClient, error) {
	stream, err := sc.client.SubscribeToTelemetrySettings(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to subscribeToTelemetrySettings: %w", err)
	}

	return stream, nil
}

// Shutdown retrieves the current application shutdown
func (sc *EnvClient) Shutdown(ctx context.Context, req *cline.EmptyRequest) (*cline.Empty, error) {
	resp, err := sc.client.Shutdown(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest shutdown: %w", err)
	}

	return resp, nil
}
