// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	cline "github.com/cline/cli/pkg/generated/cline"
	proto "github.com/cline/cli/pkg/generated/cline"
	"google.golang.org/grpc"
)

// ModelsClient wraps the generated ModelsService gRPC client
type ModelsClient struct {
	client proto.ModelsServiceClient
}

// NewModelsClient creates a new ModelsClient
func NewModelsClient(conn *grpc.ClientConn) *ModelsClient {
	return &ModelsClient{
		client: proto.NewModelsServiceClient(conn),
	}
}

// GetOllamaModels retrieves the current application getOllamaModels
func (sc *ModelsClient) GetOllamaModels(ctx context.Context, req *cline.StringRequest) (*proto.StringArray, error) {
	resp, err := sc.client.GetOllamaModels(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getOllamaModels: %w", err)
	}

	return resp, nil
}

// GetLmStudioModels retrieves the current application getLmStudioModels
func (sc *ModelsClient) GetLmStudioModels(ctx context.Context, req *cline.StringRequest) (*proto.StringArray, error) {
	resp, err := sc.client.GetLmStudioModels(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getLmStudioModels: %w", err)
	}

	return resp, nil
}

// GetVsCodeLmModels retrieves the current application getVsCodeLmModels
func (sc *ModelsClient) GetVsCodeLmModels(ctx context.Context, req *cline.EmptyRequest) (*proto.VsCodeLmModelsArray, error) {
	resp, err := sc.client.GetVsCodeLmModels(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getVsCodeLmModels: %w", err)
	}

	return resp, nil
}

// RefreshOpenRouterModelsRpc retrieves the current application refreshOpenRouterModelsRpc
func (sc *ModelsClient) RefreshOpenRouterModelsRpc(ctx context.Context, req *cline.EmptyRequest) (*proto.OpenRouterCompatibleModelInfo, error) {
	resp, err := sc.client.RefreshOpenRouterModelsRpc(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest refreshOpenRouterModelsRpc: %w", err)
	}

	return resp, nil
}

// RefreshHuggingFaceModels retrieves the current application refreshHuggingFaceModels
func (sc *ModelsClient) RefreshHuggingFaceModels(ctx context.Context, req *cline.EmptyRequest) (*proto.OpenRouterCompatibleModelInfo, error) {
	resp, err := sc.client.RefreshHuggingFaceModels(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest refreshHuggingFaceModels: %w", err)
	}

	return resp, nil
}

// RefreshOpenAiModels retrieves the current application refreshOpenAiModels
func (sc *ModelsClient) RefreshOpenAiModels(ctx context.Context, req *proto.OpenAiModelsRequest) (*proto.StringArray, error) {
	resp, err := sc.client.RefreshOpenAiModels(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest refreshOpenAiModels: %w", err)
	}

	return resp, nil
}

// RefreshVercelAiGatewayModelsRpc retrieves the current application refreshVercelAiGatewayModelsRpc
func (sc *ModelsClient) RefreshVercelAiGatewayModelsRpc(ctx context.Context, req *cline.EmptyRequest) (*proto.OpenRouterCompatibleModelInfo, error) {
	resp, err := sc.client.RefreshVercelAiGatewayModelsRpc(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest refreshVercelAiGatewayModelsRpc: %w", err)
	}

	return resp, nil
}

// RefreshRequestyModels retrieves the current application refreshRequestyModels
func (sc *ModelsClient) RefreshRequestyModels(ctx context.Context, req *cline.EmptyRequest) (*proto.OpenRouterCompatibleModelInfo, error) {
	resp, err := sc.client.RefreshRequestyModels(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest refreshRequestyModels: %w", err)
	}

	return resp, nil
}

// SubscribeToOpenRouterModels subscribes to subscribeToOpenRouterModels updates and returns a stream
func (sc *ModelsClient) SubscribeToOpenRouterModels(ctx context.Context, req *cline.EmptyRequest) (proto.ModelsService_SubscribeToOpenRouterModelsClient, error) {
	stream, err := sc.client.SubscribeToOpenRouterModels(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to subscribeToOpenRouterModels: %w", err)
	}

	return stream, nil
}

// UpdateApiConfigurationProto retrieves the current application updateApiConfigurationProto
func (sc *ModelsClient) UpdateApiConfigurationProto(ctx context.Context, req *proto.UpdateApiConfigurationRequest) (*cline.Empty, error) {
	resp, err := sc.client.UpdateApiConfigurationProto(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest updateApiConfigurationProto: %w", err)
	}

	return resp, nil
}

// UpdateApiConfigurationPartial retrieves the current application updateApiConfigurationPartial
func (sc *ModelsClient) UpdateApiConfigurationPartial(ctx context.Context, req *proto.UpdateApiConfigurationPartialRequest) (*cline.Empty, error) {
	resp, err := sc.client.UpdateApiConfigurationPartial(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest updateApiConfigurationPartial: %w", err)
	}

	return resp, nil
}

// RefreshGroqModelsRpc retrieves the current application refreshGroqModelsRpc
func (sc *ModelsClient) RefreshGroqModelsRpc(ctx context.Context, req *cline.EmptyRequest) (*proto.OpenRouterCompatibleModelInfo, error) {
	resp, err := sc.client.RefreshGroqModelsRpc(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest refreshGroqModelsRpc: %w", err)
	}

	return resp, nil
}

// RefreshBasetenModelsRpc retrieves the current application refreshBasetenModelsRpc
func (sc *ModelsClient) RefreshBasetenModelsRpc(ctx context.Context, req *cline.EmptyRequest) (*proto.OpenRouterCompatibleModelInfo, error) {
	resp, err := sc.client.RefreshBasetenModelsRpc(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest refreshBasetenModelsRpc: %w", err)
	}

	return resp, nil
}

// GetSapAiCoreModels retrieves the current application getSapAiCoreModels
func (sc *ModelsClient) GetSapAiCoreModels(ctx context.Context, req *proto.SapAiCoreModelsRequest) (*proto.SapAiCoreModelsResponse, error) {
	resp, err := sc.client.GetSapAiCoreModels(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getSapAiCoreModels: %w", err)
	}

	return resp, nil
}

// RefreshOcaModels retrieves the current application refreshOcaModels
func (sc *ModelsClient) RefreshOcaModels(ctx context.Context, req *cline.StringRequest) (*proto.OcaCompatibleModelInfo, error) {
	resp, err := sc.client.RefreshOcaModels(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest refreshOcaModels: %w", err)
	}

	return resp, nil
}
