// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	cline "github.com/cline/cli/pkg/generated/cline"
	proto "github.com/cline/cli/pkg/generated/cline"
	"google.golang.org/grpc"
)

// OcaaccountClient wraps the generated OcaAccountService gRPC client
type OcaaccountClient struct {
	client proto.OcaAccountServiceClient
}

// NewOcaaccountClient creates a new OcaaccountClient
func NewOcaaccountClient(conn *grpc.ClientConn) *OcaaccountClient {
	return &OcaaccountClient{
		client: proto.NewOcaAccountServiceClient(conn),
	}
}

// OcaAccountLoginClicked retrieves the current application ocaAccountLoginClicked
func (sc *OcaaccountClient) OcaAccountLoginClicked(ctx context.Context, req *cline.EmptyRequest) (*cline.String, error) {
	resp, err := sc.client.OcaAccountLoginClicked(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest ocaAccountLoginClicked: %w", err)
	}

	return resp, nil
}

// OcaAccountLogoutClicked retrieves the current application ocaAccountLogoutClicked
func (sc *OcaaccountClient) OcaAccountLogoutClicked(ctx context.Context, req *cline.EmptyRequest) (*cline.Empty, error) {
	resp, err := sc.client.OcaAccountLogoutClicked(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest ocaAccountLogoutClicked: %w", err)
	}

	return resp, nil
}

// OcaSubscribeToAuthStatusUpdate subscribes to ocaSubscribeToAuthStatusUpdate updates and returns a stream
func (sc *OcaaccountClient) OcaSubscribeToAuthStatusUpdate(ctx context.Context, req *cline.EmptyRequest) (proto.OcaAccountService_OcaSubscribeToAuthStatusUpdateClient, error) {
	stream, err := sc.client.OcaSubscribeToAuthStatusUpdate(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to ocaSubscribeToAuthStatusUpdate: %w", err)
	}

	return stream, nil
}
