// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	cline "github.com/cline/cli/pkg/generated/cline"
	proto "github.com/cline/cli/pkg/generated/cline"
	"google.golang.org/grpc"
)

// SlashClient wraps the generated SlashService gRPC client
type SlashClient struct {
	client proto.SlashServiceClient
}

// NewSlashClient creates a new SlashClient
func NewSlashClient(conn *grpc.ClientConn) *SlashClient {
	return &SlashClient{
		client: proto.NewSlashServiceClient(conn),
	}
}

// ReportBug retrieves the current application reportBug
func (sc *SlashClient) ReportBug(ctx context.Context, req *cline.StringRequest) (*cline.Empty, error) {
	resp, err := sc.client.ReportBug(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest reportBug: %w", err)
	}

	return resp, nil
}

// Condense retrieves the current application condense
func (sc *SlashClient) Condense(ctx context.Context, req *cline.StringRequest) (*cline.Empty, error) {
	resp, err := sc.client.Condense(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest condense: %w", err)
	}

	return resp, nil
}
