// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	cline "github.com/cline/cli/pkg/generated/cline"
	proto "github.com/cline/cli/pkg/generated/cline"
	"google.golang.org/grpc"
)

// StateClient wraps the generated StateService gRPC client
type StateClient struct {
	client proto.StateServiceClient
}

// NewStateClient creates a new StateClient
func NewStateClient(conn *grpc.ClientConn) *StateClient {
	return &StateClient{
		client: proto.NewStateServiceClient(conn),
	}
}

// GetLatestState retrieves the current application getLatestState
func (sc *StateClient) GetLatestState(ctx context.Context, req *cline.EmptyRequest) (*proto.State, error) {
	resp, err := sc.client.GetLatestState(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getLatestState: %w", err)
	}

	return resp, nil
}

// UpdateTerminalConnectionTimeout retrieves the current application updateTerminalConnectionTimeout
func (sc *StateClient) UpdateTerminalConnectionTimeout(ctx context.Context, req *proto.UpdateTerminalConnectionTimeoutRequest) (*proto.UpdateTerminalConnectionTimeoutResponse, error) {
	resp, err := sc.client.UpdateTerminalConnectionTimeout(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest updateTerminalConnectionTimeout: %w", err)
	}

	return resp, nil
}

// UpdateTerminalReuseEnabled retrieves the current application updateTerminalReuseEnabled
func (sc *StateClient) UpdateTerminalReuseEnabled(ctx context.Context, req *proto.BooleanRequest) (*cline.Empty, error) {
	resp, err := sc.client.UpdateTerminalReuseEnabled(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest updateTerminalReuseEnabled: %w", err)
	}

	return resp, nil
}

// GetAvailableTerminalProfiles retrieves the current application getAvailableTerminalProfiles
func (sc *StateClient) GetAvailableTerminalProfiles(ctx context.Context, req *cline.EmptyRequest) (*proto.TerminalProfiles, error) {
	resp, err := sc.client.GetAvailableTerminalProfiles(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getAvailableTerminalProfiles: %w", err)
	}

	return resp, nil
}

// SubscribeToState subscribes to subscribeToState updates and returns a stream
func (sc *StateClient) SubscribeToState(ctx context.Context, req *cline.EmptyRequest) (proto.StateService_SubscribeToStateClient, error) {
	stream, err := sc.client.SubscribeToState(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to subscribeToState: %w", err)
	}

	return stream, nil
}

// ToggleFavoriteModel retrieves the current application toggleFavoriteModel
func (sc *StateClient) ToggleFavoriteModel(ctx context.Context, req *cline.StringRequest) (*cline.Empty, error) {
	resp, err := sc.client.ToggleFavoriteModel(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest toggleFavoriteModel: %w", err)
	}

	return resp, nil
}

// ResetState retrieves the current application resetState
func (sc *StateClient) ResetState(ctx context.Context, req *proto.ResetStateRequest) (*cline.Empty, error) {
	resp, err := sc.client.ResetState(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest resetState: %w", err)
	}

	return resp, nil
}

// TogglePlanActModeProto retrieves the current application togglePlanActModeProto
func (sc *StateClient) TogglePlanActModeProto(ctx context.Context, req *proto.TogglePlanActModeRequest) (*proto.Boolean, error) {
	resp, err := sc.client.TogglePlanActModeProto(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest togglePlanActModeProto: %w", err)
	}

	return resp, nil
}

// UpdateAutoApprovalSettings retrieves the current application updateAutoApprovalSettings
func (sc *StateClient) UpdateAutoApprovalSettings(ctx context.Context, req *proto.AutoApprovalSettingsRequest) (*cline.Empty, error) {
	resp, err := sc.client.UpdateAutoApprovalSettings(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest updateAutoApprovalSettings: %w", err)
	}

	return resp, nil
}

// UpdateSettings retrieves the current application updateSettings
func (sc *StateClient) UpdateSettings(ctx context.Context, req *proto.UpdateSettingsRequest) (*cline.Empty, error) {
	resp, err := sc.client.UpdateSettings(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest updateSettings: %w", err)
	}

	return resp, nil
}

// UpdateSettingsCli retrieves the current application updateSettingsCli
func (sc *StateClient) UpdateSettingsCli(ctx context.Context, req *proto.UpdateSettingsRequestCli) (*cline.Empty, error) {
	resp, err := sc.client.UpdateSettingsCli(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest updateSettingsCli: %w", err)
	}

	return resp, nil
}

// UpdateTaskSettings retrieves the current application updateTaskSettings
func (sc *StateClient) UpdateTaskSettings(ctx context.Context, req *proto.UpdateTaskSettingsRequest) (*cline.Empty, error) {
	resp, err := sc.client.UpdateTaskSettings(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest updateTaskSettings: %w", err)
	}

	return resp, nil
}

// UpdateTelemetrySetting retrieves the current application updateTelemetrySetting
func (sc *StateClient) UpdateTelemetrySetting(ctx context.Context, req *proto.TelemetrySettingRequest) (*cline.Empty, error) {
	resp, err := sc.client.UpdateTelemetrySetting(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest updateTelemetrySetting: %w", err)
	}

	return resp, nil
}

// SetWelcomeViewCompleted retrieves the current application setWelcomeViewCompleted
func (sc *StateClient) SetWelcomeViewCompleted(ctx context.Context, req *proto.BooleanRequest) (*cline.Empty, error) {
	resp, err := sc.client.SetWelcomeViewCompleted(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest setWelcomeViewCompleted: %w", err)
	}

	return resp, nil
}

// UpdateInfoBannerVersion retrieves the current application updateInfoBannerVersion
func (sc *StateClient) UpdateInfoBannerVersion(ctx context.Context, req *cline.Int64Request) (*cline.Empty, error) {
	resp, err := sc.client.UpdateInfoBannerVersion(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest updateInfoBannerVersion: %w", err)
	}

	return resp, nil
}

// UpdateModelBannerVersion retrieves the current application updateModelBannerVersion
func (sc *StateClient) UpdateModelBannerVersion(ctx context.Context, req *cline.Int64Request) (*cline.Empty, error) {
	resp, err := sc.client.UpdateModelBannerVersion(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest updateModelBannerVersion: %w", err)
	}

	return resp, nil
}

// UpdateCliBannerVersion retrieves the current application updateCliBannerVersion
func (sc *StateClient) UpdateCliBannerVersion(ctx context.Context, req *cline.Int64Request) (*cline.Empty, error) {
	resp, err := sc.client.UpdateCliBannerVersion(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest updateCliBannerVersion: %w", err)
	}

	return resp, nil
}

// InstallClineCli retrieves the current application installClineCli
func (sc *StateClient) InstallClineCli(ctx context.Context, req *cline.EmptyRequest) (*cline.Empty, error) {
	resp, err := sc.client.InstallClineCli(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest installClineCli: %w", err)
	}

	return resp, nil
}

// CheckCliInstallation retrieves the current application checkCliInstallation
func (sc *StateClient) CheckCliInstallation(ctx context.Context, req *cline.EmptyRequest) (*proto.Boolean, error) {
	resp, err := sc.client.CheckCliInstallation(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest checkCliInstallation: %w", err)
	}

	return resp, nil
}

// GetProcessInfo retrieves the current application getProcessInfo
func (sc *StateClient) GetProcessInfo(ctx context.Context, req *cline.EmptyRequest) (*proto.ProcessInfo, error) {
	resp, err := sc.client.GetProcessInfo(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getProcessInfo: %w", err)
	}

	return resp, nil
}
