// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	cline "github.com/cline/cli/pkg/generated/cline"
	proto "github.com/cline/cli/pkg/generated/cline"
	"google.golang.org/grpc"
)

// TaskClient wraps the generated TaskService gRPC client
type TaskClient struct {
	client proto.TaskServiceClient
}

// NewTaskClient creates a new TaskClient
func NewTaskClient(conn *grpc.ClientConn) *TaskClient {
	return &TaskClient{
		client: proto.NewTaskServiceClient(conn),
	}
}

// CancelTask retrieves the current application cancelTask
func (sc *TaskClient) CancelTask(ctx context.Context, req *cline.EmptyRequest) (*cline.Empty, error) {
	resp, err := sc.client.CancelTask(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest cancelTask: %w", err)
	}

	return resp, nil
}

// CancelBackgroundCommand retrieves the current application cancelBackgroundCommand
func (sc *TaskClient) CancelBackgroundCommand(ctx context.Context, req *cline.EmptyRequest) (*cline.Empty, error) {
	resp, err := sc.client.CancelBackgroundCommand(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest cancelBackgroundCommand: %w", err)
	}

	return resp, nil
}

// ClearTask retrieves the current application clearTask
func (sc *TaskClient) ClearTask(ctx context.Context, req *cline.EmptyRequest) (*cline.Empty, error) {
	resp, err := sc.client.ClearTask(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest clearTask: %w", err)
	}

	return resp, nil
}

// GetTotalTasksSize retrieves the current application getTotalTasksSize
func (sc *TaskClient) GetTotalTasksSize(ctx context.Context, req *cline.EmptyRequest) (*proto.Int64, error) {
	resp, err := sc.client.GetTotalTasksSize(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getTotalTasksSize: %w", err)
	}

	return resp, nil
}

// DeleteTasksWithIds retrieves the current application deleteTasksWithIds
func (sc *TaskClient) DeleteTasksWithIds(ctx context.Context, req *proto.StringArrayRequest) (*cline.Empty, error) {
	resp, err := sc.client.DeleteTasksWithIds(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest deleteTasksWithIds: %w", err)
	}

	return resp, nil
}

// NewTask retrieves the current application newTask
func (sc *TaskClient) NewTask(ctx context.Context, req *proto.NewTaskRequest) (*cline.String, error) {
	resp, err := sc.client.NewTask(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest newTask: %w", err)
	}

	return resp, nil
}

// ShowTaskWithId retrieves the current application showTaskWithId
func (sc *TaskClient) ShowTaskWithId(ctx context.Context, req *cline.StringRequest) (*proto.TaskResponse, error) {
	resp, err := sc.client.ShowTaskWithId(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest showTaskWithId: %w", err)
	}

	return resp, nil
}

// ExportTaskWithId retrieves the current application exportTaskWithId
func (sc *TaskClient) ExportTaskWithId(ctx context.Context, req *cline.StringRequest) (*cline.Empty, error) {
	resp, err := sc.client.ExportTaskWithId(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest exportTaskWithId: %w", err)
	}

	return resp, nil
}

// ToggleTaskFavorite retrieves the current application toggleTaskFavorite
func (sc *TaskClient) ToggleTaskFavorite(ctx context.Context, req *proto.TaskFavoriteRequest) (*cline.Empty, error) {
	resp, err := sc.client.ToggleTaskFavorite(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest toggleTaskFavorite: %w", err)
	}

	return resp, nil
}

// GetTaskHistory retrieves the current application getTaskHistory
func (sc *TaskClient) GetTaskHistory(ctx context.Context, req *proto.GetTaskHistoryRequest) (*proto.TaskHistoryArray, error) {
	resp, err := sc.client.GetTaskHistory(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getTaskHistory: %w", err)
	}

	return resp, nil
}

// AskResponse retrieves the current application askResponse
func (sc *TaskClient) AskResponse(ctx context.Context, req *proto.AskResponseRequest) (*cline.Empty, error) {
	resp, err := sc.client.AskResponse(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest askResponse: %w", err)
	}

	return resp, nil
}

// TaskFeedback retrieves the current application taskFeedback
func (sc *TaskClient) TaskFeedback(ctx context.Context, req *cline.StringRequest) (*cline.Empty, error) {
	resp, err := sc.client.TaskFeedback(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest taskFeedback: %w", err)
	}

	return resp, nil
}

// TaskCompletionViewChanges retrieves the current application taskCompletionViewChanges
func (sc *TaskClient) TaskCompletionViewChanges(ctx context.Context, req *cline.Int64Request) (*cline.Empty, error) {
	resp, err := sc.client.TaskCompletionViewChanges(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest taskCompletionViewChanges: %w", err)
	}

	return resp, nil
}

// ExecuteQuickWin retrieves the current application executeQuickWin
func (sc *TaskClient) ExecuteQuickWin(ctx context.Context, req *proto.ExecuteQuickWinRequest) (*cline.Empty, error) {
	resp, err := sc.client.ExecuteQuickWin(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest executeQuickWin: %w", err)
	}

	return resp, nil
}

// DeleteAllTaskHistory retrieves the current application deleteAllTaskHistory
func (sc *TaskClient) DeleteAllTaskHistory(ctx context.Context, req *cline.EmptyRequest) (*proto.DeleteAllTaskHistoryCount, error) {
	resp, err := sc.client.DeleteAllTaskHistory(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest deleteAllTaskHistory: %w", err)
	}

	return resp, nil
}
