// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	proto "github.com/cline/cli/pkg/generated/host"
	"google.golang.org/grpc"
)

// TestingClient wraps the generated TestingService gRPC client
type TestingClient struct {
	client proto.TestingServiceClient
}

// NewTestingClient creates a new TestingClient
func NewTestingClient(conn *grpc.ClientConn) *TestingClient {
	return &TestingClient{
		client: proto.NewTestingServiceClient(conn),
	}
}

// GetWebviewHtml retrieves the current application getWebviewHtml
func (sc *TestingClient) GetWebviewHtml(ctx context.Context, req *proto.GetWebviewHtmlRequest) (*proto.GetWebviewHtmlResponse, error) {
	resp, err := sc.client.GetWebviewHtml(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getWebviewHtml: %w", err)
	}

	return resp, nil
}
