// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	cline "github.com/cline/cli/pkg/generated/cline"
	proto "github.com/cline/cli/pkg/generated/cline"
	"google.golang.org/grpc"
)

// UiClient wraps the generated UiService gRPC client
type UiClient struct {
	client proto.UiServiceClient
}

// NewUiClient creates a new UiClient
func NewUiClient(conn *grpc.ClientConn) *UiClient {
	return &UiClient{
		client: proto.NewUiServiceClient(conn),
	}
}

// ScrollToSettings retrieves the current application scrollToSettings
func (sc *UiClient) ScrollToSettings(ctx context.Context, req *cline.StringRequest) (*cline.KeyValuePair, error) {
	resp, err := sc.client.ScrollToSettings(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest scrollToSettings: %w", err)
	}

	return resp, nil
}

// SetTerminalExecutionMode retrieves the current application setTerminalExecutionMode
func (sc *UiClient) SetTerminalExecutionMode(ctx context.Context, req *proto.BooleanRequest) (*cline.KeyValuePair, error) {
	resp, err := sc.client.SetTerminalExecutionMode(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest setTerminalExecutionMode: %w", err)
	}

	return resp, nil
}

// OnDidShowAnnouncement retrieves the current application onDidShowAnnouncement
func (sc *UiClient) OnDidShowAnnouncement(ctx context.Context, req *cline.EmptyRequest) (*proto.Boolean, error) {
	resp, err := sc.client.OnDidShowAnnouncement(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest onDidShowAnnouncement: %w", err)
	}

	return resp, nil
}

// SubscribeToAddToInput subscribes to subscribeToAddToInput updates and returns a stream
func (sc *UiClient) SubscribeToAddToInput(ctx context.Context, req *cline.EmptyRequest) (proto.UiService_SubscribeToAddToInputClient, error) {
	stream, err := sc.client.SubscribeToAddToInput(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to subscribeToAddToInput: %w", err)
	}

	return stream, nil
}

// SubscribeToMcpButtonClicked subscribes to subscribeToMcpButtonClicked updates and returns a stream
func (sc *UiClient) SubscribeToMcpButtonClicked(ctx context.Context, req *cline.EmptyRequest) (proto.UiService_SubscribeToMcpButtonClickedClient, error) {
	stream, err := sc.client.SubscribeToMcpButtonClicked(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to subscribeToMcpButtonClicked: %w", err)
	}

	return stream, nil
}

// SubscribeToHistoryButtonClicked subscribes to subscribeToHistoryButtonClicked updates and returns a stream
func (sc *UiClient) SubscribeToHistoryButtonClicked(ctx context.Context, req *cline.EmptyRequest) (proto.UiService_SubscribeToHistoryButtonClickedClient, error) {
	stream, err := sc.client.SubscribeToHistoryButtonClicked(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to subscribeToHistoryButtonClicked: %w", err)
	}

	return stream, nil
}

// SubscribeToChatButtonClicked subscribes to subscribeToChatButtonClicked updates and returns a stream
func (sc *UiClient) SubscribeToChatButtonClicked(ctx context.Context, req *cline.EmptyRequest) (proto.UiService_SubscribeToChatButtonClickedClient, error) {
	stream, err := sc.client.SubscribeToChatButtonClicked(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to subscribeToChatButtonClicked: %w", err)
	}

	return stream, nil
}

// SubscribeToAccountButtonClicked subscribes to subscribeToAccountButtonClicked updates and returns a stream
func (sc *UiClient) SubscribeToAccountButtonClicked(ctx context.Context, req *cline.EmptyRequest) (proto.UiService_SubscribeToAccountButtonClickedClient, error) {
	stream, err := sc.client.SubscribeToAccountButtonClicked(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to subscribeToAccountButtonClicked: %w", err)
	}

	return stream, nil
}

// SubscribeToSettingsButtonClicked subscribes to subscribeToSettingsButtonClicked updates and returns a stream
func (sc *UiClient) SubscribeToSettingsButtonClicked(ctx context.Context, req *cline.EmptyRequest) (proto.UiService_SubscribeToSettingsButtonClickedClient, error) {
	stream, err := sc.client.SubscribeToSettingsButtonClicked(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to subscribeToSettingsButtonClicked: %w", err)
	}

	return stream, nil
}

// SubscribeToPartialMessage subscribes to subscribeToPartialMessage updates and returns a stream
func (sc *UiClient) SubscribeToPartialMessage(ctx context.Context, req *cline.EmptyRequest) (proto.UiService_SubscribeToPartialMessageClient, error) {
	stream, err := sc.client.SubscribeToPartialMessage(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to subscribeToPartialMessage: %w", err)
	}

	return stream, nil
}

// InitializeWebview retrieves the current application initializeWebview
func (sc *UiClient) InitializeWebview(ctx context.Context, req *cline.EmptyRequest) (*cline.Empty, error) {
	resp, err := sc.client.InitializeWebview(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest initializeWebview: %w", err)
	}

	return resp, nil
}

// SubscribeToRelinquishControl subscribes to subscribeToRelinquishControl updates and returns a stream
func (sc *UiClient) SubscribeToRelinquishControl(ctx context.Context, req *cline.EmptyRequest) (proto.UiService_SubscribeToRelinquishControlClient, error) {
	stream, err := sc.client.SubscribeToRelinquishControl(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to subscribeToRelinquishControl: %w", err)
	}

	return stream, nil
}

// SubscribeToFocusChatInput subscribes to subscribeToFocusChatInput updates and returns a stream
func (sc *UiClient) SubscribeToFocusChatInput(ctx context.Context, req *cline.EmptyRequest) (proto.UiService_SubscribeToFocusChatInputClient, error) {
	stream, err := sc.client.SubscribeToFocusChatInput(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to subscribeToFocusChatInput: %w", err)
	}

	return stream, nil
}

// SubscribeToDidBecomeVisible subscribes to subscribeToDidBecomeVisible updates and returns a stream
func (sc *UiClient) SubscribeToDidBecomeVisible(ctx context.Context, req *cline.EmptyRequest) (proto.UiService_SubscribeToDidBecomeVisibleClient, error) {
	stream, err := sc.client.SubscribeToDidBecomeVisible(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to subscribe to subscribeToDidBecomeVisible: %w", err)
	}

	return stream, nil
}

// GetWebviewHtml retrieves the current application getWebviewHtml
func (sc *UiClient) GetWebviewHtml(ctx context.Context, req *cline.EmptyRequest) (*cline.String, error) {
	resp, err := sc.client.GetWebviewHtml(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getWebviewHtml: %w", err)
	}

	return resp, nil
}

// OpenUrl retrieves the current application openUrl
func (sc *UiClient) OpenUrl(ctx context.Context, req *cline.StringRequest) (*cline.Empty, error) {
	resp, err := sc.client.OpenUrl(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest openUrl: %w", err)
	}

	return resp, nil
}

// OpenWalkthrough retrieves the current application openWalkthrough
func (sc *UiClient) OpenWalkthrough(ctx context.Context, req *cline.EmptyRequest) (*cline.Empty, error) {
	resp, err := sc.client.OpenWalkthrough(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest openWalkthrough: %w", err)
	}

	return resp, nil
}
