// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	cline "github.com/cline/cli/pkg/generated/cline"
	proto "github.com/cline/cli/pkg/generated/cline"
	"google.golang.org/grpc"
)

// WebClient wraps the generated WebService gRPC client
type WebClient struct {
	client proto.WebServiceClient
}

// NewWebClient creates a new WebClient
func NewWebClient(conn *grpc.ClientConn) *WebClient {
	return &WebClient{
		client: proto.NewWebServiceClient(conn),
	}
}

// CheckIsImageUrl retrieves the current application checkIsImageUrl
func (sc *WebClient) CheckIsImageUrl(ctx context.Context, req *cline.StringRequest) (*proto.IsImageUrl, error) {
	resp, err := sc.client.CheckIsImageUrl(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest checkIsImageUrl: %w", err)
	}

	return resp, nil
}

// FetchOpenGraphData retrieves the current application fetchOpenGraphData
func (sc *WebClient) FetchOpenGraphData(ctx context.Context, req *cline.StringRequest) (*proto.OpenGraphData, error) {
	resp, err := sc.client.FetchOpenGraphData(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest fetchOpenGraphData: %w", err)
	}

	return resp, nil
}

// OpenInBrowser retrieves the current application openInBrowser
func (sc *WebClient) OpenInBrowser(ctx context.Context, req *cline.StringRequest) (*cline.Empty, error) {
	resp, err := sc.client.OpenInBrowser(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest openInBrowser: %w", err)
	}

	return resp, nil
}
