// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	proto "github.com/cline/cli/pkg/generated/host"
	"google.golang.org/grpc"
)

// WindowClient wraps the generated WindowService gRPC client
type WindowClient struct {
	client proto.WindowServiceClient
}

// NewWindowClient creates a new WindowClient
func NewWindowClient(conn *grpc.ClientConn) *WindowClient {
	return &WindowClient{
		client: proto.NewWindowServiceClient(conn),
	}
}

// ShowTextDocument retrieves the current application showTextDocument
func (sc *WindowClient) ShowTextDocument(ctx context.Context, req *proto.ShowTextDocumentRequest) (*proto.TextEditorInfo, error) {
	resp, err := sc.client.ShowTextDocument(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest showTextDocument: %w", err)
	}

	return resp, nil
}

// ShowOpenDialogue retrieves the current application showOpenDialogue
func (sc *WindowClient) ShowOpenDialogue(ctx context.Context, req *proto.ShowOpenDialogueRequest) (*proto.SelectedResources, error) {
	resp, err := sc.client.ShowOpenDialogue(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest showOpenDialogue: %w", err)
	}

	return resp, nil
}

// ShowMessage retrieves the current application showMessage
func (sc *WindowClient) ShowMessage(ctx context.Context, req *proto.ShowMessageRequest) (*proto.SelectedResponse, error) {
	resp, err := sc.client.ShowMessage(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest showMessage: %w", err)
	}

	return resp, nil
}

// ShowInputBox retrieves the current application showInputBox
func (sc *WindowClient) ShowInputBox(ctx context.Context, req *proto.ShowInputBoxRequest) (*proto.ShowInputBoxResponse, error) {
	resp, err := sc.client.ShowInputBox(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest showInputBox: %w", err)
	}

	return resp, nil
}

// ShowSaveDialog retrieves the current application showSaveDialog
func (sc *WindowClient) ShowSaveDialog(ctx context.Context, req *proto.ShowSaveDialogRequest) (*proto.ShowSaveDialogResponse, error) {
	resp, err := sc.client.ShowSaveDialog(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest showSaveDialog: %w", err)
	}

	return resp, nil
}

// OpenFile retrieves the current application openFile
func (sc *WindowClient) OpenFile(ctx context.Context, req *proto.OpenFileRequest) (*proto.OpenFileResponse, error) {
	resp, err := sc.client.OpenFile(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest openFile: %w", err)
	}

	return resp, nil
}

// OpenSettings retrieves the current application openSettings
func (sc *WindowClient) OpenSettings(ctx context.Context, req *proto.OpenSettingsRequest) (*proto.OpenSettingsResponse, error) {
	resp, err := sc.client.OpenSettings(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest openSettings: %w", err)
	}

	return resp, nil
}

// GetOpenTabs retrieves the current application getOpenTabs
func (sc *WindowClient) GetOpenTabs(ctx context.Context, req *proto.GetOpenTabsRequest) (*proto.GetOpenTabsResponse, error) {
	resp, err := sc.client.GetOpenTabs(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getOpenTabs: %w", err)
	}

	return resp, nil
}

// GetVisibleTabs retrieves the current application getVisibleTabs
func (sc *WindowClient) GetVisibleTabs(ctx context.Context, req *proto.GetVisibleTabsRequest) (*proto.GetVisibleTabsResponse, error) {
	resp, err := sc.client.GetVisibleTabs(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getVisibleTabs: %w", err)
	}

	return resp, nil
}

// GetActiveEditor retrieves the current application getActiveEditor
func (sc *WindowClient) GetActiveEditor(ctx context.Context, req *proto.GetActiveEditorRequest) (*proto.GetActiveEditorResponse, error) {
	resp, err := sc.client.GetActiveEditor(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getActiveEditor: %w", err)
	}

	return resp, nil
}
