// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package services

import (
	"context"
	"fmt"

	proto "github.com/cline/cli/pkg/generated/host"
	"google.golang.org/grpc"
)

// WorkspaceClient wraps the generated WorkspaceService gRPC client
type WorkspaceClient struct {
	client proto.WorkspaceServiceClient
}

// NewWorkspaceClient creates a new WorkspaceClient
func NewWorkspaceClient(conn *grpc.ClientConn) *WorkspaceClient {
	return &WorkspaceClient{
		client: proto.NewWorkspaceServiceClient(conn),
	}
}

// GetWorkspacePaths retrieves the current application getWorkspacePaths
func (sc *WorkspaceClient) GetWorkspacePaths(ctx context.Context, req *proto.GetWorkspacePathsRequest) (*proto.GetWorkspacePathsResponse, error) {
	resp, err := sc.client.GetWorkspacePaths(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getWorkspacePaths: %w", err)
	}

	return resp, nil
}

// SaveOpenDocumentIfDirty retrieves the current application saveOpenDocumentIfDirty
func (sc *WorkspaceClient) SaveOpenDocumentIfDirty(ctx context.Context, req *proto.SaveOpenDocumentIfDirtyRequest) (*proto.SaveOpenDocumentIfDirtyResponse, error) {
	resp, err := sc.client.SaveOpenDocumentIfDirty(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest saveOpenDocumentIfDirty: %w", err)
	}

	return resp, nil
}

// GetDiagnostics retrieves the current application getDiagnostics
func (sc *WorkspaceClient) GetDiagnostics(ctx context.Context, req *proto.GetDiagnosticsRequest) (*proto.GetDiagnosticsResponse, error) {
	resp, err := sc.client.GetDiagnostics(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest getDiagnostics: %w", err)
	}

	return resp, nil
}

// OpenProblemsPanel retrieves the current application openProblemsPanel
func (sc *WorkspaceClient) OpenProblemsPanel(ctx context.Context, req *proto.OpenProblemsPanelRequest) (*proto.OpenProblemsPanelResponse, error) {
	resp, err := sc.client.OpenProblemsPanel(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest openProblemsPanel: %w", err)
	}

	return resp, nil
}

// OpenInFileExplorerPanel retrieves the current application openInFileExplorerPanel
func (sc *WorkspaceClient) OpenInFileExplorerPanel(ctx context.Context, req *proto.OpenInFileExplorerPanelRequest) (*proto.OpenInFileExplorerPanelResponse, error) {
	resp, err := sc.client.OpenInFileExplorerPanel(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest openInFileExplorerPanel: %w", err)
	}

	return resp, nil
}

// OpenClineSidebarPanel retrieves the current application openClineSidebarPanel
func (sc *WorkspaceClient) OpenClineSidebarPanel(ctx context.Context, req *proto.OpenClineSidebarPanelRequest) (*proto.OpenClineSidebarPanelResponse, error) {
	resp, err := sc.client.OpenClineSidebarPanel(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest openClineSidebarPanel: %w", err)
	}

	return resp, nil
}

// OpenTerminalPanel retrieves the current application openTerminalPanel
func (sc *WorkspaceClient) OpenTerminalPanel(ctx context.Context, req *proto.OpenTerminalRequest) (*proto.OpenTerminalResponse, error) {
	resp, err := sc.client.OpenTerminalPanel(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest openTerminalPanel: %w", err)
	}

	return resp, nil
}

// ExecuteCommandInTerminal retrieves the current application executeCommandInTerminal
func (sc *WorkspaceClient) ExecuteCommandInTerminal(ctx context.Context, req *proto.ExecuteCommandInTerminalRequest) (*proto.ExecuteCommandInTerminalResponse, error) {
	resp, err := sc.client.ExecuteCommandInTerminal(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to get latest executeCommandInTerminal: %w", err)
	}

	return resp, nil
}
