// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by scripts/build-go-proto.mjs

package client

import (
	"context"
	"fmt"
	"sync"

	"google.golang.org/grpc"
	"github.com/cline/cli/client/services"
)

// ClineClient provides a unified interface to all Cline services
type ClineClient struct {
	connManager *ConnectionManager
	
	// Service clients
	Account *services.AccountClient
	Browser *services.BrowserClient
	Checkpoints *services.CheckpointsClient
	Commands *services.CommandsClient
	Dictation *services.DictationClient
	File *services.FileClient
	Mcp *services.McpClient
	Models *services.ModelsClient
	Ocaaccount *services.OcaaccountClient
	Slash *services.SlashClient
	State *services.StateClient
	Task *services.TaskClient
	Ui *services.UiClient
	Web *services.WebClient
	Diff *services.DiffClient
	Env *services.EnvClient
	Testing *services.TestingClient
	Window *services.WindowClient
	Workspace *services.WorkspaceClient
	
	// Connection state
	mutex     sync.RWMutex
	connected bool
}

// NewClineClient creates a new unified Cline client
func NewClineClient(address string) (*ClineClient, error) {
	config := &ConnectionConfig{
		Address: address,
	}
	
	connManager := NewConnectionManager(config)
	
	return &ClineClient{
		connManager: connManager,
	}, nil
}

// NewClineClientWithConfig creates a new Cline client with custom configuration
func NewClineClientWithConfig(config *ConnectionConfig) (*ClineClient, error) {
	connManager := NewConnectionManager(config)
	
	return &ClineClient{
		connManager: connManager,
	}, nil
}

// Connect establishes connection to Cline Core and initializes service clients
func (c *ClineClient) Connect(ctx context.Context) error {
	c.mutex.Lock()
	defer c.mutex.Unlock()
	
	if c.connected {
		return nil
	}
	
	// Establish gRPC connection
	if err := c.connManager.Connect(ctx); err != nil {
		return fmt.Errorf("failed to connect: %w", err)
	}
	
	// Initialize service clients
	conn := c.connManager.GetConnection()
	c.Account = services.NewAccountClient(conn)
	c.Browser = services.NewBrowserClient(conn)
	c.Checkpoints = services.NewCheckpointsClient(conn)
	c.Commands = services.NewCommandsClient(conn)
	c.Dictation = services.NewDictationClient(conn)
	c.File = services.NewFileClient(conn)
	c.Mcp = services.NewMcpClient(conn)
	c.Models = services.NewModelsClient(conn)
	c.Ocaaccount = services.NewOcaaccountClient(conn)
	c.Slash = services.NewSlashClient(conn)
	c.State = services.NewStateClient(conn)
	c.Task = services.NewTaskClient(conn)
	c.Ui = services.NewUiClient(conn)
	c.Web = services.NewWebClient(conn)
	c.Diff = services.NewDiffClient(conn)
	c.Env = services.NewEnvClient(conn)
	c.Testing = services.NewTestingClient(conn)
	c.Window = services.NewWindowClient(conn)
	c.Workspace = services.NewWorkspaceClient(conn)
	
	c.connected = true
	return nil
}

// Disconnect closes the connection to Cline Core
func (c *ClineClient) Disconnect() error {
	c.mutex.Lock()
	defer c.mutex.Unlock()
	
	if !c.connected {
		return nil
	}
	
	err := c.connManager.Disconnect()
	c.connected = false
	
	// Clear service clients
	c.Account = nil
	c.Browser = nil
	c.Checkpoints = nil
	c.Commands = nil
	c.Dictation = nil
	c.File = nil
	c.Mcp = nil
	c.Models = nil
	c.Ocaaccount = nil
	c.Slash = nil
	c.State = nil
	c.Task = nil
	c.Ui = nil
	c.Web = nil
	c.Diff = nil
	c.Env = nil
	c.Testing = nil
	c.Window = nil
	c.Workspace = nil
	
	return err
}

// IsConnected returns true if the client is connected to Cline Core
func (c *ClineClient) IsConnected() bool {
	c.mutex.RLock()
	defer c.mutex.RUnlock()
	return c.connected
}

// Reconnect closes the current connection and establishes a new one
func (c *ClineClient) Reconnect(ctx context.Context) error {
	c.mutex.Lock()
	defer c.mutex.Unlock()
	
	// Disconnect first
	if c.connected {
		if err := c.connManager.Disconnect(); err != nil {
			return fmt.Errorf("failed to disconnect: %w", err)
		}
		c.connected = false
	}
	
	// Reconnect
	if err := c.connManager.Connect(ctx); err != nil {
		return fmt.Errorf("failed to reconnect: %w", err)
	}
	
	// Reinitialize service clients
	conn := c.connManager.GetConnection()
	c.Account = services.NewAccountClient(conn)
	c.Browser = services.NewBrowserClient(conn)
	c.Checkpoints = services.NewCheckpointsClient(conn)
	c.Commands = services.NewCommandsClient(conn)
	c.Dictation = services.NewDictationClient(conn)
	c.File = services.NewFileClient(conn)
	c.Mcp = services.NewMcpClient(conn)
	c.Models = services.NewModelsClient(conn)
	c.Ocaaccount = services.NewOcaaccountClient(conn)
	c.Slash = services.NewSlashClient(conn)
	c.State = services.NewStateClient(conn)
	c.Task = services.NewTaskClient(conn)
	c.Ui = services.NewUiClient(conn)
	c.Web = services.NewWebClient(conn)
	c.Diff = services.NewDiffClient(conn)
	c.Env = services.NewEnvClient(conn)
	c.Testing = services.NewTestingClient(conn)
	c.Window = services.NewWindowClient(conn)
	c.Workspace = services.NewWorkspaceClient(conn)
	
	c.connected = true
	return nil
}

// GetConnection returns the underlying gRPC connection
func (c *ClineClient) GetConnection() *grpc.ClientConn {
	return c.connManager.GetConnection()
}
